services:
  - type: web
    name: hygiatrade-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hygiatrade-api.onrender.com/api
