"use client";

import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { useSelector } from "react-redux";
import { StarIcon } from "@heroicons/react/24/solid";
import { toast } from "react-toastify";
import { RootState } from "../store";
import { formatCurrency } from "../utils/currency";
import { useLanguageTheme } from "../i18n/LanguageThemeContext";
import ProductActions from "../components/products/ProductActions";

type ProductImage = { id: string | null; uri: string };
type Product = { id:string; title:string; description:string; regularPrice:number; mainImageUrl:string; secondaryImages?:ProductImage[]; categoryId:string; categoryName?:string; brand?:string; quantity:number; rating?:number; discountPercentage?:number; discountedPrice?:number; };
type ReviewItem = { id:string; content:string; rating:number; createdOn:string; userId:string; userNames:string; };

const ProductDetails = () => {
  const { id } = useParams<{ id: string }>();
  const token = useSelector((state: RootState) => state.auth.token);
  const { language } = useLanguageTheme();
  const isBg = language === "bg";
  const tr = (bg:string,en:string)=>(isBg?bg:en);
  const [product,setProduct]=useState<Product|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selectedImage,setSelectedImage]=useState(0); const [quantity,setQuantity]=useState(1); const [reviews,setReviews]=useState<ReviewItem[]>([]); const [pageNumber]=useState(1); const [totalPages,setTotalPages]=useState(1); const [sortBy]=useState("createdOn"); const [sortDescending]=useState(true); const pageSize=5;
  const resolveProductId=async(routeValue:string)=>{if(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(routeValue))return routeValue;const tokenPart=routeValue.match(/-([0-9a-f]{8})$/i)?.[1]?.toLowerCase();if(!tokenPart)return routeValue;const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Products?PageNumber=1&PageSize=500`);if(!r.ok)return routeValue;const d=await r.json();const list=Array.isArray(d)?d:Array.isArray(d?.items)?d.items:[];return list.find((p:Product)=>String(p.id).replace(/-/g,"").toLowerCase().startsWith(tokenPart))?.id??routeValue;};
  useEffect(()=>{if(!id)return;let cancelled=false;(async()=>{try{setLoading(true);setError(null);const realId=await resolveProductId(id);const response=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Products/${realId}`);if(!response.ok)throw new Error(tr("Продуктът не можа да бъде зареден.","We could not load this product."));const data=await response.json() as Product;if(!cancelled){setProduct(data);setQuantity(1);setSelectedImage(0);}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:tr("Продуктът не можа да бъде зареден.","We could not load this product."));}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[id,language]);
  useEffect(()=>{if(!product?.id)return;(async()=>{try{const q=new URLSearchParams({ProductId:product.id,PageNumber:String(pageNumber),PageSize:String(pageSize),SortBy:sortBy,SortDescending:String(sortDescending)});const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Reviews?${q}`,{headers:token?{Authorization:`Bearer ${token}`} : undefined});if(!r.ok)return;const d=await r.json();setReviews(Array.isArray(d.items)?d.items:[]);setTotalPages(Math.max(1,Math.ceil(Number(d.totalCount??0)/pageSize)));}catch{}})();},[product?.id,pageNumber,sortBy,sortDescending,token,language]);
  const addToCart=async()=>{if(!product)return;if(!token){toast.error(tr("Влез в профила си, за да добавиш продукта в количката.","Sign in to add this product to your cart."));return;}try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL}/Orders`,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({productId:product.id,quantity})});if(!r.ok)throw 0;toast.success(tr("Продуктът е добавен в количката.","Product added to cart."));}catch{toast.error(tr("Продуктът не можа да бъде добавен в количката.","We could not add this product to your cart."));}};
  if(loading)return <div className="flex min-h-[55vh] items-center justify-center"><div className="h-11 w-11 animate-spin rounded-full border-4 border-slate-200 border-t-[#18b99f]"/></div>;
  if(error||!product)return <div className="flex min-h-[55vh] items-center justify-center px-4 text-center text-red-600">{error||tr("Продуктът не е намерен.","Product not found.")}</div>;
  const images=[product.mainImageUrl,...(product.secondaryImages??[]).map(x=>x.uri)].filter(Boolean);const displayPrice=product.discountedPrice&&product.discountedPrice>0?product.discountedPrice:product.regularPrice;const rating=Number(product.rating??0);
  return <main className="min-h-[calc(100vh-4rem)] bg-slate-50 px-3 py-5 sm:px-6 sm:py-8 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(360px,0.9fr)] lg:gap-10"><section><div className="relative aspect-square overflow-hidden rounded-[2rem] border bg-white"><img src={images[selectedImage]||"/placeholder-image.jpg"} alt={product.title} className="h-full w-full object-contain p-6"/></div></section><section className="rounded-[2rem] border bg-white p-6 lg:p-8"><div className="text-xs font-semibold uppercase text-slate-500">{product.brand}{product.categoryName?` • ${product.categoryName}`:""}</div><h1 className="mt-3 text-4xl font-bold">{product.title}</h1><div className="mt-4 flex">{[1,2,3,4,5].map(s=><StarIcon key={s} className={`h-5 w-5 ${s<=Math.round(rating)?"text-yellow-400":"text-slate-200"}`}/>)}</div><div className="mt-6 text-3xl font-black">{formatCurrency(displayPrice)}</div><div className="mt-6 border-y py-4"><strong className={product.quantity>0?"text-emerald-700":"text-rose-600"}>{product.quantity>0?tr("В наличност","In stock"):tr("Няма наличност","Out of stock")}</strong> · {product.quantity} {tr("бр.","pcs")}</div><div className="prose prose-sm mt-6" dangerouslySetInnerHTML={{__html:product.description||""}}/>{product.quantity>0&&<div className="mt-6 flex items-center gap-3"><button onClick={()=>setQuantity(Math.max(1,quantity-1))}>−</button><input type="number" min={1} max={product.quantity} value={quantity} onChange={e=>setQuantity(Math.min(product.quantity,Math.max(1,Number(e.target.value)||1)))} className="w-20 rounded border p-2 text-center"/><button onClick={()=>setQuantity(Math.min(product.quantity,quantity+1))}>+</button></div>}<button onClick={()=>void addToCart()} disabled={product.quantity<=0} className="mt-6 w-full rounded-xl bg-slate-950 px-5 py-3 font-bold text-white disabled:opacity-40">{tr("Добави в количката","Add to cart")}</button><ProductActions productId={product.id} showLabels /></section></div><div className="hidden">{reviews.length}{totalPages}</div></div></main>;
};
export default ProductDetails;
